//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeTracker.SmartBbiService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Negocio", Namespace="http://schemas.datacontract.org/2004/07/WebServiceCommon.Modelos.H")]
    [System.SerializableAttribute()]
    public partial class Negocio : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long CodigoClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CodigoContraparteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoISINField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoNegociacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommodityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DMAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataPregaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HoraMinutoNegocioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NUM_SEQ_RPSS_PARCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NaturezaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal NumNegocioCodigoNegField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PrecoExercicioOpcaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PrecoNegocioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal QuantidadeNegocioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoMercadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime VencimentoContratoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal VlDolarDr1Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long CodigoCliente {
            get {
                return this.CodigoClienteField;
            }
            set {
                if ((this.CodigoClienteField.Equals(value) != true)) {
                    this.CodigoClienteField = value;
                    this.RaisePropertyChanged("CodigoCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CodigoContraparte {
            get {
                return this.CodigoContraparteField;
            }
            set {
                if ((this.CodigoContraparteField.Equals(value) != true)) {
                    this.CodigoContraparteField = value;
                    this.RaisePropertyChanged("CodigoContraparte");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoISIN {
            get {
                return this.CodigoISINField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoISINField, value) != true)) {
                    this.CodigoISINField = value;
                    this.RaisePropertyChanged("CodigoISIN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoNegociacao {
            get {
                return this.CodigoNegociacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoNegociacaoField, value) != true)) {
                    this.CodigoNegociacaoField = value;
                    this.RaisePropertyChanged("CodigoNegociacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Commodity {
            get {
                return this.CommodityField;
            }
            set {
                if ((object.ReferenceEquals(this.CommodityField, value) != true)) {
                    this.CommodityField = value;
                    this.RaisePropertyChanged("Commodity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DMA {
            get {
                return this.DMAField;
            }
            set {
                if ((object.ReferenceEquals(this.DMAField, value) != true)) {
                    this.DMAField = value;
                    this.RaisePropertyChanged("DMA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataPregao {
            get {
                return this.DataPregaoField;
            }
            set {
                if ((this.DataPregaoField.Equals(value) != true)) {
                    this.DataPregaoField = value;
                    this.RaisePropertyChanged("DataPregao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HoraMinutoNegocio {
            get {
                return this.HoraMinutoNegocioField;
            }
            set {
                if ((object.ReferenceEquals(this.HoraMinutoNegocioField, value) != true)) {
                    this.HoraMinutoNegocioField = value;
                    this.RaisePropertyChanged("HoraMinutoNegocio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NUM_SEQ_RPSS_PARC {
            get {
                return this.NUM_SEQ_RPSS_PARCField;
            }
            set {
                if ((object.ReferenceEquals(this.NUM_SEQ_RPSS_PARCField, value) != true)) {
                    this.NUM_SEQ_RPSS_PARCField = value;
                    this.RaisePropertyChanged("NUM_SEQ_RPSS_PARC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Natureza {
            get {
                return this.NaturezaField;
            }
            set {
                if ((object.ReferenceEquals(this.NaturezaField, value) != true)) {
                    this.NaturezaField = value;
                    this.RaisePropertyChanged("Natureza");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal NumNegocioCodigoNeg {
            get {
                return this.NumNegocioCodigoNegField;
            }
            set {
                if ((this.NumNegocioCodigoNegField.Equals(value) != true)) {
                    this.NumNegocioCodigoNegField = value;
                    this.RaisePropertyChanged("NumNegocioCodigoNeg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PrecoExercicioOpcao {
            get {
                return this.PrecoExercicioOpcaoField;
            }
            set {
                if ((this.PrecoExercicioOpcaoField.Equals(value) != true)) {
                    this.PrecoExercicioOpcaoField = value;
                    this.RaisePropertyChanged("PrecoExercicioOpcao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PrecoNegocio {
            get {
                return this.PrecoNegocioField;
            }
            set {
                if ((this.PrecoNegocioField.Equals(value) != true)) {
                    this.PrecoNegocioField = value;
                    this.RaisePropertyChanged("PrecoNegocio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal QuantidadeNegocio {
            get {
                return this.QuantidadeNegocioField;
            }
            set {
                if ((this.QuantidadeNegocioField.Equals(value) != true)) {
                    this.QuantidadeNegocioField = value;
                    this.RaisePropertyChanged("QuantidadeNegocio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoMercado {
            get {
                return this.TipoMercadoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoMercadoField, value) != true)) {
                    this.TipoMercadoField = value;
                    this.RaisePropertyChanged("TipoMercado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime VencimentoContrato {
            get {
                return this.VencimentoContratoField;
            }
            set {
                if ((this.VencimentoContratoField.Equals(value) != true)) {
                    this.VencimentoContratoField = value;
                    this.RaisePropertyChanged("VencimentoContrato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal VlDolarDr1 {
            get {
                return this.VlDolarDr1Field;
            }
            set {
                if ((this.VlDolarDr1Field.Equals(value) != true)) {
                    this.VlDolarDr1Field = value;
                    this.RaisePropertyChanged("VlDolarDr1");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SmartBbiService.IWServiceSMBrad")]
    public interface IWServiceSMBrad {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWServiceSMBrad/ObtemNegocios", ReplyAction="http://tempuri.org/IWServiceSMBrad/ObtemNegociosResponse")]
        string ObtemNegocios(string Usuario, string Senha, string Data, string Conta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWServiceSMBrad/ObtemNegocios", ReplyAction="http://tempuri.org/IWServiceSMBrad/ObtemNegociosResponse")]
        System.Threading.Tasks.Task<string> ObtemNegociosAsync(string Usuario, string Senha, string Data, string Conta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWServiceSMBrad/GarantiasDepositadas", ReplyAction="http://tempuri.org/IWServiceSMBrad/GarantiasDepositadasResponse")]
        string GarantiasDepositadas(string Usuario, string Senha, string Data, string Conta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWServiceSMBrad/GarantiasDepositadas", ReplyAction="http://tempuri.org/IWServiceSMBrad/GarantiasDepositadasResponse")]
        System.Threading.Tasks.Task<string> GarantiasDepositadasAsync(string Usuario, string Senha, string Data, string Conta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWServiceSMBrad/ObtemMargem", ReplyAction="http://tempuri.org/IWServiceSMBrad/ObtemMargemResponse")]
        string ObtemMargem(string Usuario, string Senha, string Data, string Conta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWServiceSMBrad/ObtemMargem", ReplyAction="http://tempuri.org/IWServiceSMBrad/ObtemMargemResponse")]
        System.Threading.Tasks.Task<string> ObtemMargemAsync(string Usuario, string Senha, string Data, string Conta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWServiceSMBrad/CustosOperacionais", ReplyAction="http://tempuri.org/IWServiceSMBrad/CustosOperacionaisResponse")]
        string CustosOperacionais(string Usuario, string Senha, string Data, string Conta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWServiceSMBrad/CustosOperacionais", ReplyAction="http://tempuri.org/IWServiceSMBrad/CustosOperacionaisResponse")]
        System.Threading.Tasks.Task<string> CustosOperacionaisAsync(string Usuario, string Senha, string Data, string Conta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWServiceSMBrad/GetNegocios", ReplyAction="http://tempuri.org/IWServiceSMBrad/GetNegociosResponse")]
        TradeTracker.SmartBbiService.Negocio[] GetNegocios(string Usuario, string Senha, string Data, string Conta, long SEQ_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWServiceSMBrad/GetNegocios", ReplyAction="http://tempuri.org/IWServiceSMBrad/GetNegociosResponse")]
        System.Threading.Tasks.Task<TradeTracker.SmartBbiService.Negocio[]> GetNegociosAsync(string Usuario, string Senha, string Data, string Conta, long SEQ_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWServiceSMBrad/CustosOperacionaisBOV", ReplyAction="http://tempuri.org/IWServiceSMBrad/CustosOperacionaisBOVResponse")]
        string CustosOperacionaisBOV(string Usuario, string Senha, string Data, string Conta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWServiceSMBrad/CustosOperacionaisBOV", ReplyAction="http://tempuri.org/IWServiceSMBrad/CustosOperacionaisBOVResponse")]
        System.Threading.Tasks.Task<string> CustosOperacionaisBOVAsync(string Usuario, string Senha, string Data, string Conta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWServiceSMBrad/ObtemNegociosBOV", ReplyAction="http://tempuri.org/IWServiceSMBrad/ObtemNegociosBOVResponse")]
        string ObtemNegociosBOV(string Usuario, string Senha, string Data, string Conta, bool negscasa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWServiceSMBrad/ObtemNegociosBOV", ReplyAction="http://tempuri.org/IWServiceSMBrad/ObtemNegociosBOVResponse")]
        System.Threading.Tasks.Task<string> ObtemNegociosBOVAsync(string Usuario, string Senha, string Data, string Conta, bool negscasa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWServiceSMBrad/SimulaRisco", ReplyAction="http://tempuri.org/IWServiceSMBrad/SimulaRiscoResponse")]
        string SimulaRisco(string Usuario, string Senha, string Conta, string Params);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWServiceSMBrad/SimulaRisco", ReplyAction="http://tempuri.org/IWServiceSMBrad/SimulaRiscoResponse")]
        System.Threading.Tasks.Task<string> SimulaRiscoAsync(string Usuario, string Senha, string Conta, string Params);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWServiceSMBrad/ObtemAluguelPosAber", ReplyAction="http://tempuri.org/IWServiceSMBrad/ObtemAluguelPosAberResponse")]
        string ObtemAluguelPosAber(string Usuario, string Senha, string Data, string Conta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWServiceSMBrad/ObtemAluguelPosAber", ReplyAction="http://tempuri.org/IWServiceSMBrad/ObtemAluguelPosAberResponse")]
        System.Threading.Tasks.Task<string> ObtemAluguelPosAberAsync(string Usuario, string Senha, string Data, string Conta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWServiceSMBrad/ObtemAluguelMovNovos", ReplyAction="http://tempuri.org/IWServiceSMBrad/ObtemAluguelMovNovosResponse")]
        string ObtemAluguelMovNovos(string Usuario, string Senha, string Data, string Conta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWServiceSMBrad/ObtemAluguelMovNovos", ReplyAction="http://tempuri.org/IWServiceSMBrad/ObtemAluguelMovNovosResponse")]
        System.Threading.Tasks.Task<string> ObtemAluguelMovNovosAsync(string Usuario, string Senha, string Data, string Conta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWServiceSMBrad/ObtemAluguelMovRenov", ReplyAction="http://tempuri.org/IWServiceSMBrad/ObtemAluguelMovRenovResponse")]
        string ObtemAluguelMovRenov(string Usuario, string Senha, string Data, string Conta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWServiceSMBrad/ObtemAluguelMovRenov", ReplyAction="http://tempuri.org/IWServiceSMBrad/ObtemAluguelMovRenovResponse")]
        System.Threading.Tasks.Task<string> ObtemAluguelMovRenovAsync(string Usuario, string Senha, string Data, string Conta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWServiceSMBrad/ObtemAluguelMovLiq", ReplyAction="http://tempuri.org/IWServiceSMBrad/ObtemAluguelMovLiqResponse")]
        string ObtemAluguelMovLiq(string Usuario, string Senha, string Data, string Conta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWServiceSMBrad/ObtemAluguelMovLiq", ReplyAction="http://tempuri.org/IWServiceSMBrad/ObtemAluguelMovLiqResponse")]
        System.Threading.Tasks.Task<string> ObtemAluguelMovLiqAsync(string Usuario, string Senha, string Data, string Conta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWServiceSMBrad/SetParam", ReplyAction="http://tempuri.org/IWServiceSMBrad/SetParamResponse")]
        string SetParam(string Usuario, string Senha, string Param);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWServiceSMBrad/SetParam", ReplyAction="http://tempuri.org/IWServiceSMBrad/SetParamResponse")]
        System.Threading.Tasks.Task<string> SetParamAsync(string Usuario, string Senha, string Param);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWServiceSMBradChannel : TradeTracker.SmartBbiService.IWServiceSMBrad, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WServiceSMBradClient : System.ServiceModel.ClientBase<TradeTracker.SmartBbiService.IWServiceSMBrad>, TradeTracker.SmartBbiService.IWServiceSMBrad {
        
        public WServiceSMBradClient() {
        }
        
        public WServiceSMBradClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WServiceSMBradClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WServiceSMBradClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WServiceSMBradClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ObtemNegocios(string Usuario, string Senha, string Data, string Conta) {
            return base.Channel.ObtemNegocios(Usuario, Senha, Data, Conta);
        }
        
        public System.Threading.Tasks.Task<string> ObtemNegociosAsync(string Usuario, string Senha, string Data, string Conta) {
            return base.Channel.ObtemNegociosAsync(Usuario, Senha, Data, Conta);
        }
        
        public string GarantiasDepositadas(string Usuario, string Senha, string Data, string Conta) {
            return base.Channel.GarantiasDepositadas(Usuario, Senha, Data, Conta);
        }
        
        public System.Threading.Tasks.Task<string> GarantiasDepositadasAsync(string Usuario, string Senha, string Data, string Conta) {
            return base.Channel.GarantiasDepositadasAsync(Usuario, Senha, Data, Conta);
        }
        
        public string ObtemMargem(string Usuario, string Senha, string Data, string Conta) {
            return base.Channel.ObtemMargem(Usuario, Senha, Data, Conta);
        }
        
        public System.Threading.Tasks.Task<string> ObtemMargemAsync(string Usuario, string Senha, string Data, string Conta) {
            return base.Channel.ObtemMargemAsync(Usuario, Senha, Data, Conta);
        }
        
        public string CustosOperacionais(string Usuario, string Senha, string Data, string Conta) {
            return base.Channel.CustosOperacionais(Usuario, Senha, Data, Conta);
        }
        
        public System.Threading.Tasks.Task<string> CustosOperacionaisAsync(string Usuario, string Senha, string Data, string Conta) {
            return base.Channel.CustosOperacionaisAsync(Usuario, Senha, Data, Conta);
        }
        
        public TradeTracker.SmartBbiService.Negocio[] GetNegocios(string Usuario, string Senha, string Data, string Conta, long SEQ_ID) {
            return base.Channel.GetNegocios(Usuario, Senha, Data, Conta, SEQ_ID);
        }
        
        public System.Threading.Tasks.Task<TradeTracker.SmartBbiService.Negocio[]> GetNegociosAsync(string Usuario, string Senha, string Data, string Conta, long SEQ_ID) {
            return base.Channel.GetNegociosAsync(Usuario, Senha, Data, Conta, SEQ_ID);
        }
        
        public string CustosOperacionaisBOV(string Usuario, string Senha, string Data, string Conta) {
            return base.Channel.CustosOperacionaisBOV(Usuario, Senha, Data, Conta);
        }
        
        public System.Threading.Tasks.Task<string> CustosOperacionaisBOVAsync(string Usuario, string Senha, string Data, string Conta) {
            return base.Channel.CustosOperacionaisBOVAsync(Usuario, Senha, Data, Conta);
        }
        
        public string ObtemNegociosBOV(string Usuario, string Senha, string Data, string Conta, bool negscasa) {
            return base.Channel.ObtemNegociosBOV(Usuario, Senha, Data, Conta, negscasa);
        }
        
        public System.Threading.Tasks.Task<string> ObtemNegociosBOVAsync(string Usuario, string Senha, string Data, string Conta, bool negscasa) {
            return base.Channel.ObtemNegociosBOVAsync(Usuario, Senha, Data, Conta, negscasa);
        }
        
        public string SimulaRisco(string Usuario, string Senha, string Conta, string Params) {
            return base.Channel.SimulaRisco(Usuario, Senha, Conta, Params);
        }
        
        public System.Threading.Tasks.Task<string> SimulaRiscoAsync(string Usuario, string Senha, string Conta, string Params) {
            return base.Channel.SimulaRiscoAsync(Usuario, Senha, Conta, Params);
        }
        
        public string ObtemAluguelPosAber(string Usuario, string Senha, string Data, string Conta) {
            return base.Channel.ObtemAluguelPosAber(Usuario, Senha, Data, Conta);
        }
        
        public System.Threading.Tasks.Task<string> ObtemAluguelPosAberAsync(string Usuario, string Senha, string Data, string Conta) {
            return base.Channel.ObtemAluguelPosAberAsync(Usuario, Senha, Data, Conta);
        }
        
        public string ObtemAluguelMovNovos(string Usuario, string Senha, string Data, string Conta) {
            return base.Channel.ObtemAluguelMovNovos(Usuario, Senha, Data, Conta);
        }
        
        public System.Threading.Tasks.Task<string> ObtemAluguelMovNovosAsync(string Usuario, string Senha, string Data, string Conta) {
            return base.Channel.ObtemAluguelMovNovosAsync(Usuario, Senha, Data, Conta);
        }
        
        public string ObtemAluguelMovRenov(string Usuario, string Senha, string Data, string Conta) {
            return base.Channel.ObtemAluguelMovRenov(Usuario, Senha, Data, Conta);
        }
        
        public System.Threading.Tasks.Task<string> ObtemAluguelMovRenovAsync(string Usuario, string Senha, string Data, string Conta) {
            return base.Channel.ObtemAluguelMovRenovAsync(Usuario, Senha, Data, Conta);
        }
        
        public string ObtemAluguelMovLiq(string Usuario, string Senha, string Data, string Conta) {
            return base.Channel.ObtemAluguelMovLiq(Usuario, Senha, Data, Conta);
        }
        
        public System.Threading.Tasks.Task<string> ObtemAluguelMovLiqAsync(string Usuario, string Senha, string Data, string Conta) {
            return base.Channel.ObtemAluguelMovLiqAsync(Usuario, Senha, Data, Conta);
        }
        
        public string SetParam(string Usuario, string Senha, string Param) {
            return base.Channel.SetParam(Usuario, Senha, Param);
        }
        
        public System.Threading.Tasks.Task<string> SetParamAsync(string Usuario, string Senha, string Param) {
            return base.Channel.SetParamAsync(Usuario, Senha, Param);
        }
    }
}
